nifi1:
  # image: aperepel/nifi
  build: .
  ports:
    # keep the same port number across instances,
    # this will ensure Swarm distributes the containers
    # properly based on port anti-affinity
    - 9091:8080
  net: nifi
  environment:
    NIFI_UI_BANNER_TEXT: 'Acquisition Node'

nifi2:
  # image: aperepel/nifi
  build: .
  ports:
    - 9091:8080
  net: nifi
  environment:
    NIFI_UI_BANNER_TEXT: 'Processing Node'
