acquisition:
  # image: aperepel/nifi
  build: .
  ports:
    # keep the same port number across instances,
    # this will ensure Swarm distributes the containers
    # properly based on port anti-affinity
    - 9091:8080
  net: nifi
  environment:
    NIFI_UI_BANNER_TEXT: 'Acquisition Node'
  # have to fix the container name until
  # https://github.com/docker/compose/issues/2312 is addressed
  container_name: acquisition

processing-1:
  # image: aperepel/nifi
  build: .
  ports:
    - 9091:8080
  net: nifi
  environment:
    NIFI_UI_BANNER_TEXT: 'Processing Node'
  container_name: processing-1

processing-2:
  # image: aperepel/nifi
  build: .
  ports:
    - 9092:8080
  net: nifi
  environment:
    NIFI_UI_BANNER_TEXT: 'Processing Node'
  container_name: processing-2
