version: '2'

networks:
  default:
    driver: overlay


services:

  acquisition:
    image: aperepel/nifi
    # build: ../docker/
    ports:
      # keep the same port number across instances,
      # this will ensure Swarm distributes the containers
      # properly based on port anti-affinity
      - 9091:8080
      - 10000
      - 10001
      - 10002
      - 10003
      - 10004
    volumes:
      - /etc/security/nifi/keytabs:/etc/security/nifi/keytabs:ro
      - /HDPCONFIGPATH:/mnt/nifi:ro
    environment:
      NIFI_UI_BANNER_TEXT: 'Acquisition Node'
      NIFI_INSTANCE_ROLE: 'edge'
      ENV NIFI_JAVA_MINHEAP: '-Xmx256m'
      ENV NIFI_JAVA_MAXHEAP: '-Xmx256m'

  ncm:
    image: aperepel/nifi
    # build: ../docker/
    ports:
      - 9092:8080
    volumes:
      - /etc/security/nifi/keytabs:/etc/security/nifi/keytabs
      - /mnt/nifi:/mnt/nifi:ro
    environment:
      NIFI_UI_BANNER_TEXT: 'Processing Cluster'
      NIFI_INSTANCE_ROLE: 'cluster-manager'
      ENV NIFI_JAVA_MINHEAP: '-Xmx256m'
      ENV NIFI_JAVA_MAXHEAP: '-Xmx256m'
      #constraint:node: '=NODENAME'

  worker:
    image: aperepel/nifi
    # build: ../docker/
    ports:
      - 10000
      - 10001
      - 10002
      - 10003
      - 10004
    volumes:
      - /etc/security/nifi/keytabs:/etc/security/nifi/keytabs
      - /HDPCONFIGPATH:/mnt/nifi:ro
      - /mnt/swarm/nifi:/scripts:ro
    environment:
      NIFI_UI_BANNER_TEXT: 'Processing Node'
      NIFI_INSTANCE_ROLE: 'cluster-node'
      ENV NIFI_JAVA_MINHEAP: '-Xmx256m'
      ENV NIFI_JAVA_MAXHEAP: '-Xmx256m'